[package]
name = "application"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
common = { path = "../common" }
domain = { path = "../domain" }
chrono = { workspace = true }
chrono-tz = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
rand = { workspace = true }
async-trait = { workspace = true }
fluent = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
schemars = { workspace = true }
