FROM ubuntu:24.04

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y \
    curl \
    build-essential \
    pkg-config \
    libssl-dev \
    libopus-dev

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /workspace
